db.url=jdbc:mysql://localhost:3306/YOUR_DATABASE
db.user=YOUR_DATABASE_USER
db.password=YOUR_DATABASE_PASSWORD
db.table=users
jwt.secretkey=YOUR_JWT_SECRET
mail.id=YOUR_EMAIL
mail.secretkey=YOUR_EMAIL_APP_PASSWORD